### ISSUE TITLE
please provide apk

### ISSUE THREAD

**Issue by rzr** [artetxem/mitzuli#10]
Or also make it buildable for non googlized android devices : 
https://f-droid.org/wiki/page/com.mitzuli

**Comment by artetxem** [comment]
There were some build issues with F-Droid and the app was temporarily retired from it. I am working on it right now and the app should soon be republished there (in fact, I already have a fix, but there are more things that I want to do before I push the changes).

As for distributing the raw apk, that's something that I have in mind, but I would first like to implement an update checking mechanism for the app, because most people would probably miss updates otherwise and I would then have to support old versions in the server side.

**Comment by rzr** [comment]
Ok I see your point, consider to upload to other store but fdroid should be enough 

Thx for all

**Comment by artetxem** [comment]
The app has finally been republished at F-Droid.
