### ISSUE TITLE
No audio TTS

### ISSUE THREAD

**Issue by moshpirit** [artetxem/mitzuli#20]
Hi, I'm trying to learn Portuguese and for the option Spanish → Portuguese there's no option to use the TTS and hear the words. Am I missing something?

**Comment by artetxem** [comment]
Mitzuli uses your preferred TTS engine as specified in 'Languages & input' → 'Text-to-speech output' → 'Preferred engine' under the system settings. If the preferred engine does not support the language in question it uses any other installed engine that does support it. So you if you want to use this feature in Portuguese you will have to install a TTS engine that supports this language. Most devices have 'Google Text-to-speech' preinstalled but you can find many alternatives such as SVOX, IVONA or eSpeak TTS in Google Play or other stores.

**Comment by moshpirit** [comment]
I see, so it depends of any other app. Tried eSpeak but it crashes and can't report it because it uses google code :( 
SVOX and IVONA are not on F-droid so I'm not using them. 
No way to create a "TTS-plugin for Mitzuli"?

Thanks anyway!

**Comment by artetxem** [comment]
Mitzuli does not come with its own TTS engine and it will never do, first because it makes little sense given the modular architecture of Android in this regard (the user can install any engine they want and Mitzuli simply uses it, no need to reinvent the wheel), and second because implementing a TTS engine from scratch that supports all the languages available in Mitzuli would be an extremely complex and difficult project and I don't have the time, resources and knowledge that is necessary for that.

I don't know of any TTS engine that is in F-droid apart from eSpeak and as you say the latter doesn't seem to be maintained anymore. As said before you can install other (non open source) alternatives from other sources. But this is not an issue with Mitzuli itself so I am closing it.
