### ISSUE TITLE
Crash when translate a photo

### ISSUE THREAD

**Issue by diegstroyer** [artetxem/mitzuli#7]

**Comment by artetxem** [comment]
Please give us more details: your device, android version, where you downloaded the app from, if you are able to reproduce the error, when and how the app crashes (can you see the preview? does the app crash as soon as you press the translate button?)...

**Comment by diegstroyer** [comment]
Model: Thl-t6s (chinesse phone)
Android: 4.4.2
App downloaded from: f-droid
App version: 1.0.0
The app crash when click translate button, I can see the preview, but when click translate, crash.
The other options works fine.

**Comment by artetxem** [comment]
Thanks @diegstroyer.

There is a build issue with the F-Droid version of Mitzuli. The OCR libraries are missing on it, and that's why the app crashes when you take a photo. It was not me who submitted the app to F-Droid, so this is not completely under my control, but I will have a look at the build issues and see if I can do something. In the meantime, if you are ok with Google Play you can download the proper version from there (also, the F-Droid version will always miss my API keys, which means that it will never be fully functional, so I think that the Google Play version will always be preferable unless you have something in particular against that store).

**Comment by diegstroyer** [comment]
Ok, the google play version works perfect. The app can translate the photo text without crash.
Thanks.

Enviado desde mi teléfono con K-9 Mail.

**Comment by artetxem** [comment]
The app has been republished at F-Droid and the reported issue is fixed.
